"""Deterministic pilot schedule and fail-closed configuration freezer."""

import argparse
import json
import time
from itertools import product
from pathlib import Path

import numpy as np

from .config import load_config
from .io import atomic_json, sha256_file, sha256_json
from .registry import load_registry


def pilot_status(expected_manifest, raw_dir):
    manifest = json.loads(Path(expected_manifest).read_text(encoding="ascii"))
    raw_dir = Path(raw_dir)
    counts = {key: 0 for key in ("expected", "computed", "reused", "invalid", "missing", "conflict")}
    fingerprints = {}
    tasks = manifest.get("tasks", manifest.get("tuning_tasks", []))
    counts["expected"] = len(tasks)
    for task in tasks:
        fingerprint = sha256_json(task)
        matches = list(raw_dir.rglob(f"{fingerprint}*.npz"))
        if not matches:
            counts["missing"] += 1
            continue
        hashes = {sha256_file(path) for path in matches}
        if len(hashes) > 1:
            counts["conflict"] += 1
            continue
        with np.load(matches[0], allow_pickle=False) as data:
            if str(data["task_fingerprint"].item()) != fingerprint:
                counts["conflict"] += 1
            elif not bool(data["valid"].item()):
                counts["invalid"] += 1
            else:
                counts["reused" if len(matches) > 1 else "computed"] += 1
        fingerprints[fingerprint] = sorted(str(path) for path in matches)
    return {"pilot_status_version": "exp102.pilot.status.v1", **counts, "files": fingerprints}


def pilot_schedule(registry_path, config_path, output_path):
    registry = load_registry(registry_path)
    config = load_config(config_path)
    tuning = []
    for code in registry["codes"]:
        for p in (0.04, 0.07, 0.10):
            for disorder in range(4):
                tuning.append({"stage": "tuning", "namespace": "pilot_tuning_v1",
                               "code_id": code["code_id"], "p": p, "disorder_index": disorder})
    held_out = []
    for code in registry["codes"]:
        for p in config["p_values"]:
            for disorder in range(8):
                held_out.append({"stage": "held_out", "namespace": "pilot_held_out_v1",
                                 "code_id": code["code_id"], "p": p, "disorder_index": disorder})
    candidates = [{"p_hot": ph, "num_temperatures": r, "gamma": gamma,
                   "burn_rounds": rounds[0], "measurement_rounds": rounds[1],
                   "sweeps_per_round": 1, "logical_move_repeat": 1}
                  for ph, r, gamma, rounds in product(
                      config["pilot"]["p_hot_candidates"],
                      config["pilot"]["num_temperatures_candidates"],
                      config["pilot"]["gamma_candidates"],
                      config["pilot"]["round_candidates"])]
    schedule = {"pilot_schedule_version": "exp102.pilot.v1",
                "registry_sha256": registry["registry_sha256"], "config_sha256": config["config_sha256"],
                "selection_policy": "raise_p_hot_and_R_then_min_core_time_gamma_then_raise_round_budget",
                "candidates": candidates, "tuning_tasks": tuning, "held_out_tasks": held_out}
    atomic_json(output_path, schedule)
    return schedule


def _verify_report_evidence(report, report_path):
    if report.get("generated_by") != "pilot.merge-select.v1":
        raise ValueError("pilot report was not generated by merge-select")
    evidence = report.get("raw_evidence")
    if not isinstance(evidence, list) or not evidence:
        raise ValueError("pilot report has no raw evidence")
    root = Path(report_path).resolve().parent
    seen = set()
    for item in evidence:
        if set(item) != {"path", "sha256"} or item["path"] in seen:
            raise ValueError("invalid or duplicate raw evidence entry")
        seen.add(item["path"])
        path = (root / item["path"]).resolve()
        if root not in path.parents or not path.is_file():
            raise ValueError(f"raw evidence is missing or outside report tree: {item['path']}")
        if sha256_file(path) != item["sha256"]:
            raise ValueError(f"raw evidence hash mismatch: {item['path']}")


def freeze_from_report(report_path, output_path):
    report = json.loads(Path(report_path).read_text(encoding="ascii"))
    if report.get("report_version") != "exp102.pilot.report.v1":
        raise ValueError("wrong pilot report version")
    _verify_report_evidence(report, report_path)
    by_m = report.get("by_m", {})
    if set(by_m) != {str(m) for m in range(3, 9)}:
        raise ValueError("pilot report must cover m=3..8")
    required_identity = {"registry_sha256", "config_sha256", "source_commit", "engine"}
    if not required_identity <= report.keys() or report.get("engine") != "numba":
        raise ValueError("pilot report production identity is incomplete")
    frozen = {"status": "FROZEN_HELD_OUT_PASS", "pilot_report_sha256": sha256_json(report),
              **{key: report[key] for key in required_identity}, "by_m": {}}
    required = {"p_hot", "num_temperatures", "gamma", "burn_rounds", "measurement_rounds",
                "sweeps_per_round", "logical_move_repeat"}
    for m, record in by_m.items():
        if not record.get("all_tuning_pass") or not record.get("all_held_out_pass"):
            raise ValueError(f"m={m} did not pass both pilot stages")
        if record.get("num_tuning_cells") != 96 or record.get("num_held_out_cells") != 448:
            raise ValueError(f"m={m} pilot cell count incomplete")
        selected = record.get("selected_config", {})
        if set(selected) != required:
            raise ValueError(f"m={m} selected config fields are incomplete")
        frozen["by_m"][m] = selected
    atomic_json(output_path, frozen)
    return frozen


def main(argv=None):
    parser = argparse.ArgumentParser(); sub = parser.add_subparsers(dest="command", required=True)
    schedule = sub.add_parser("schedule"); schedule.add_argument("registry"); schedule.add_argument("config"); schedule.add_argument("output")
    freeze = sub.add_parser("freeze"); freeze.add_argument("report"); freeze.add_argument("output")
    status = sub.add_parser("status"); status.add_argument("manifest"); status.add_argument("raw_dir")
    args = parser.parse_args(argv)
    if args.command == "schedule":
        result = pilot_schedule(args.registry, args.config, args.output)
    elif args.command == "freeze":
        result = freeze_from_report(args.report, args.output)
    else:
        result = pilot_status(args.manifest, args.raw_dir)
    print(sha256_json(result))


if __name__ == "__main__": main()
